-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 11:32:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `db_node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_node` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2048) NOT NULL DEFAULT '',
  `account_token` VARCHAR(64) NOT NULL DEFAULT '',
  `access_token` VARCHAR(64) NOT NULL DEFAULT '',
  `account_total` BIGINT(64) NOT NULL DEFAULT 0,
  `account_current` BIGINT(64) NOT NULL DEFAULT 0,
  `create_error` INT(32) NOT NULL DEFAULT 0,
  `poll_error` TINYINT NULL NOT NULL DEFAULT 0,
  `last_poll_success` BIGINT(64) NULL,
  `last_poll_attempt` BIGINT(64) NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL DEFAULT '',
  `password` VARCHAR(1024) NOT NULL DEFAULT '',
  `salt` VARCHAR(1024) NOT NULL DEFAULT '',
  `handle` VARCHAR(128) NULL,
  `name` VARCHAR(1024) NULL,
  `description` VARCHAR(4096) NULL,
  `location` VARCHAR(1024) NULL,
  `logo` TEXT(32187) NULL,
  `revision` INT NOT NULL DEFAULT 0,
  `registry` VARCHAR(1024) NULL,
  `node` VARCHAR(1024) NOT NULL DEFAULT '',
  `version` VARCHAR(32) NOT NULL DEFAULT '',
  `profile_revision` INT NOT NULL DEFAULT 0,
  `gps` TINYINT NOT NULL DEFAULT 0,
  `gps_longitude` FLOAT NULL,
  `gps_latitude` FLOAT NULL,
  `gps_altitude` FLOAT NULL,
  `gps_timestamp` BIGINT(64) NULL,
  `phone_number` VARCHAR(1024) NULL,
  `confirmed_phone` TINYINT NULL,
  `email_address` VARCHAR(1024) NULL,
  `confirmed_email` TINYINT NULL,
  `searchable` TINYINT NOT NULL DEFAULT 0,
  `available` TINYINT NOT NULL DEFAULT 1,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `login_token` VARCHAR(64) NULL,
  `account_token` VARCHAR(64) NULL,
  `service_token` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`login_token` ASC),
  UNIQUE INDEX `emigo_UNIQUE` (`emigo_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` INT(32) NOT NULL,
  `processor` INT NOT NULL,
  `memory` BIGINT(64) NOT NULL,
  `storage` BIGINT(64) NOT NULL,
  `requests` BIGINT(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `string_value` VARCHAR(1024) NULL,
  `num_value` BIGINT(64) NULL,
  `bool_value` TINYINT NULL,
  UNIQUE INDEX `config_id_UNIQUE` (`config_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

